name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setup environment
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.local
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.local
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.local
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env.local
          echo "JUDGE_NAME=${{ secrets.JUDGE_NAME }}" >> .env.local
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

      - name: Run Python script
        run: python render.py

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/mesenev/cats-judge:latest      
